markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Random
host: yourdomain.com
desc: 想到什么写什么

custom:
    category:
        life: 生活
        travel: 旅游
        machinelearning: 机器学习
        new: 新东西
        default: 未分类
    categories:
      - name:  life
        title: 生活杂谈

      - name:  travel
        title: 旅游
      
      - name: machinelearning
        title: 机器学习

      - name: new
        title: 新东西

      - name: default
        title: 未分类

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Jiawang
        email: ljwsummer@gmail.com
        disqus: jjff67              # Disqus缩略标识
        gcse: 001403367908376767222:sst78p7vm-w     # Google自定义搜索标识ID
        github: ljwsummer                 # GitHub账号
        gravatar: 201319267e330c98c8dcdeada8a17a97  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
